name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Python function
      run: |
        python my_module.py
        echo "{TEMP_VAR_NAME}={5}" >> $GITHUB_OUTPUT
        python -c "from my_module import my_function; print(my_function(5))"
        if [ $? -eq 0 ]; then
          echo "Success"
        else
          echo "Failure"
        fi
