name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Python function
      run: |
        python my_module.py
        echo "::set-output name={TEMP_VAR_NAME}::{5}"
        id: set_temp_var
        python -c "from my_module import my_function; print(my_function(id))"
        if [ $? -eq 0 ]; then
          echo "Success"
        else
          echo "Failure"
        fi
