name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pytest check env sushi go
        run: |
          commit_sha=${{ github.sha }}
          repo_name=${{ github.repository }}
          api_url="https://api.github.com/repos/${repo_name}/commits/${commit_sha}"
          echo "API URL: $api_url"
          changed_files=$(curl -s $api_url | jq -r '.files | .[] | .filename')
          
          echo "$changed_files"
          echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      
      - name: Run pytest check env sushi go
        run: |
          pytest -q -s --name SushiGo

